version: '3.1'
services:
  humhub:
    build: .
    container_name: humhub    
    links:
      - "db:db"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volume/config:/var/www/localhost/htdocs/protected/config"
      - "./volume/uploads:/var/www/localhost/htdocs/uploads"
      - "./volume/modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_DB_HOST: 'mariadb'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 1
      HUMHUB_DEBUG: 0
      HUMHUB_PROTO: 'https'
      HUMHUB_HOST: 'demo.rauch.lan'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: mariadb:10.4
    container_name: mariadb
    volumes:
      - "./db_mariadb/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
