name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker-compose build
    - name: Spin up services
      run: docker-compose up -d
    - name: Wait 
      run: sleep 60
    - name: Check status
      run: docker ps -a
    - name: Test
      run: curl http://localhost:8080/ -L --fail -s | grep 'Sign in</button>' -q
    - name: Test Email
      run: docker-compose exec -T humhub php /var/www/localhost/htdocs/protected/yii test/email 'test@example.com' | grep 'Message successfully sent!' -q
